$:
  # vscode 事件：专供页面中启动远程开发用
  vscode:
    - docker:
        # 自定义开发环境
        build:
          # 指定构建镜像的 Dockerfile 文件
          dockerfile: .ide/Dockerfile
          # 用来声明缓存构建过程中依赖的文件列表。
          # 注意：如果构建过程有用到其他文件，也需要在此处声明
          # 参考文档：https://docs.cnb.cool/zh/grammar/pipeline.html#build
          by:
            - .ide/php.ini
      services:
        # 声明使用 vscode 服务
        - vscode
        # 声明在容器中支持 docker 命令
        - docker
      stages:
        # 环境启动后需要执行的命令
        - name: ls
          script: ls -al

  # 推送标签时需要执行的命令
  tag_push:
    - name: docker构建推送流水线
      services:
        - docker
      stages:
        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: docker build
          script: docker build --build-arg ENV=prod -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest

    - name: 生成CodeWiki流水线
      services:
        - docker
      docker:
        volumes:
          - /data/codewiki/${CNB_REPO_SLUG}:data
      stages:
        - name: 生成 Code Wiki
          timeout: 2h
          image: cnbcool/codewiki:latest
          settings:
            git_doc_dir: /data/codewiki/${CNB_REPO_SLUG}

  push:
    - name: docker构建推送流水线
      services:
        - docker
      stages:
        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: docker build
          script: docker build --build-arg ENV=develop -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH} .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH}

    - name: 代码同步流水线
      imports:
        - https://cnb.cool/larva-cool/secret/-/blob/main/git.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/larva-cool/laravel-skel-pro.git
            auth_type: https
            username: ${GITHUB_USERNAME}
            password: ${GITHUB_ACCESS_TOKEN}
            push_tags: "true"
            force: "true"
        - name: sync to codeup
          image: tencentcom/git-sync
          settings:
            target_url: https://codeup.aliyun.com/xutongle/larva-cool/laravel-skel-pro.git
            auth_type: https
            username: ${CODEUP_USERNAME}
            password: ${CODEUP_PASSWORD}
            push_tags: "true"
            force: "true"
